// Automatically generated by scripts/build-data.py. Do not edit directly.
window.POLICY_CITATION_DATA = {
  "summary": {
    "total": 94,
    "orgs": 56,
    "countries": 19,
    "papers": 18
  },
  "top_papers": [
    {
      "paper": "Quantifying the cost savings of global solar photovoltaic supply chains",
      "citations": 26,
      "doi": "10.1038/s41586-022-05316-6"
    },
    {
      "paper": "Enabling a Rapid and Just Transition away from Coal in China",
      "citations": 9,
      "doi": "10.1016/j.oneear.2020.07.012"
    },
    {
      "paper": "Addressing carbon Offsetters’ Paradox: Lessons from Chinese wind CDM",
      "citations": 8,
      "doi": "10.1016/j.enpol.2013.09.021"
    },
    {
      "paper": "Rapid cost decrease of renewables and storage accelerates the decarbonization of China’s power system",
      "citations": 8,
      "doi": "10.1038/s41467-020-16184-x"
    },
    {
      "paper": "Challenges and opportunities for carbon neutrality in China",
      "citations": 7,
      "doi": "10.1038/s43017-021-00244-x"
    },
    {
      "paper": "ELITE cities: A low-carbon eco-city evaluation tool for China",
      "citations": 7,
      "doi": "10.1016/j.ecolind.2014.09.018"
    },
    {
      "paper": "Modeling the impact of EVs in the Chinese power system: Pathways for implementing emissions reduction commitments in the power and transportation sectors",
      "citations": 4,
      "doi": "10.1016/j.enpol.2020.111962"
    },
    {
      "paper": "SWITCH-China: A Systems Approach to Decarbonizing China’s Power System",
      "citations": 4,
      "doi": "10.1021/acs.est.6b01345"
    },
    {
      "paper": "Assessing the impacts of nuclear desalination and geoengineering to address China's water shortages",
      "citations": 2,
      "doi": "10.1016/j.desal.2014.12.028"
    },
    {
      "paper": "China reins in the spiralling construction costs of nuclear power — what can other countries learn?",
      "citations": 2,
      "doi": "10.1038/d41586-025-02341-z"
    },
    {
      "paper": "Climate change impacts on planned supply–demand match in global wind and solar energy systems",
      "citations": 2,
      "doi": "10.1038/s41560-023-01304-w"
    },
    {
      "paper": "Disentangling the drivers of carbon prices in China's ETS pilots — An EEMD approach",
      "citations": 2,
      "doi": "10.1016/j.techfore.2018.11.009"
    },
    {
      "paper": "Experiences and lessons from China’s success in providing electricity for all",
      "citations": 2,
      "doi": "10.1016/j.resconrec.2017.03.011"
    },
    {
      "paper": "Fewer than 15% of coal power plant workers in China can easily shift to green jobs by 2060",
      "citations": 2,
      "doi": "10.1016/j.oneear.2024.10.006"
    },
    {
      "paper": "Deploying solar photovoltaic energy first in carbon-intensive regions brings gigatons more carbon mitigations to 2060",
      "citations": 1,
      "doi": "10.1038/s43247-023-01006-x"
    },
    {
      "paper": "Developing large coal-power bases in China",
      "citations": 1,
      "doi": "10.1017/cbo9781316136058.003"
    },
    {
      "paper": "Relevance of Nuclear Desalination as an Alternative to Water Transfer Geoengineering Projects: Example of China",
      "citations": 1,
      "doi": "10.1016/b978-0-12-815244-7.00007-6"
    },
    {
      "paper": "Where, when and how much wind is available? A provincial-scale wind resource assessment for China",
      "citations": 1,
      "doi": "10.1016/j.enpol.2014.07.003"
    }
  ],
  "orgs": [
    {
      "org": "World Bank",
      "country": "IGO",
      "source_type": "igo",
      "citations": 7,
      "latest": "2024-08-01",
      "doc_url": "https://hdl.handle.net/10986/41919"
    },
    {
      "org": "Government of Switzerland",
      "country": "Switzerland",
      "source_type": "government",
      "citations": 5,
      "latest": "2020-04-07",
      "doc_url": "https://www.bafu.admin.ch/dam/bafu/de/dokumente/daten-karten/externe-studien-berichte/BAFU-IKTU_Schlussbericht_v1.1_2020-04.pdf.download.pdf/BAFU-IKTU_Schlussbericht_v1.1_2020-04.pdf"
    },
    {
      "org": "United Nations",
      "country": "IGO",
      "source_type": "igo",
      "citations": 5,
      "latest": "2024-08-01",
      "doc_url": "https://digitallibrary.un.org/record/4060754?ln=en"
    },
    {
      "org": "World Trade Organization",
      "country": "IGO",
      "source_type": "igo",
      "citations": 5,
      "latest": "2025-12-14",
      "doc_url": "https://www.wto.org/english/res_e/publications_e/gvcreport2025_e.htm"
    },
    {
      "org": "Grantham Institute",
      "country": "UK",
      "source_type": "think tank",
      "citations": 4,
      "latest": "2023-02-16",
      "doc_url": "https://www.lse.ac.uk/granthaminstitute/publication/embracing-the-new-paradigm-of-green-development/"
    },
    {
      "org": "International Renewable Energy Agency",
      "country": "IGO",
      "source_type": "igo",
      "citations": 3,
      "latest": "2024-10-01",
      "doc_url": "https://www.irena.org/Publications/2024/Oct/Renewable-energy-and-jobs-Annual-review-2024"
    },
    {
      "org": "New York State",
      "country": "USA",
      "source_type": "government",
      "citations": 3,
      "latest": "2022-12-15",
      "doc_url": "https://climate.ny.gov/-/media/Project/Climate/Files/Appendix-G.pdf"
    },
    {
      "org": "Publications Office of the European Union",
      "country": "EU",
      "source_type": "government",
      "citations": 3,
      "latest": "2022-06-01",
      "doc_url": "https://op.europa.eu/en/publication-detail/-/publication/31c9b68c-e21b-11ec-a534-01aa75ed71a1/language-en/format-PDF"
    },
    {
      "org": "American Enterprise Institute",
      "country": "USA",
      "source_type": "think tank",
      "citations": 2,
      "latest": "2026-06-19",
      "doc_url": "https://www.aei.org/articles/can-america-build-nuclear-again-part-3/"
    },
    {
      "org": "Banque de France",
      "country": "France",
      "source_type": "government",
      "citations": 2,
      "latest": "2024-08-27",
      "doc_url": "https://www.banque-france.fr/fr/publications-et-statistiques/publications/haute-tension-financer-la-voie-vers-la-sortie-du-charbon"
    },
    {
      "org": "Belfer Center",
      "country": "USA",
      "source_type": "think tank",
      "citations": 2,
      "latest": "2025-09-16",
      "doc_url": "https://www.belfercenter.org/research-analysis/sustaining-global-energy-transition"
    },
    {
      "org": "Center for Strategic and International Studies",
      "country": "USA",
      "source_type": "think tank",
      "citations": 2,
      "latest": "2024-02-22",
      "doc_url": "https://bigdatachina.csis.org/why-decarbonization-requires-globalization-an-interview-with-michael-davidson/"
    },
    {
      "org": "Government of Japan",
      "country": "Japan",
      "source_type": "government",
      "citations": 2,
      "latest": "2020-03-27",
      "doc_url": "https://www.env.go.jp/content/900449149.pdf"
    },
    {
      "org": "IIASA",
      "country": "Austria",
      "source_type": "think tank",
      "citations": 2,
      "latest": "2021-11-25",
      "doc_url": "https://pure.iiasa.ac.at/id/eprint/17658/?template=default_internal"
    },
    {
      "org": "Korea Energy Economics Institute",
      "country": "South Korea",
      "source_type": "think tank",
      "citations": 2,
      "latest": "2023-01-01",
      "doc_url": "https://www.nkis.re.kr/subject_view1.do?otcCd=RG&otcNm=일반연구보고서&otpId=OTP_0000000000013562&otpSeq=0&eoSeq=383869&currentPage=1&searchSelect=&searchWord=&returnPage=newest_list.do&schLclaScsId=&pblYy=&agcNms=에너지경제연구원&listPerPage=50"
    },
    {
      "org": "Science and Technology Policy Institute",
      "country": "South Korea",
      "source_type": "think tank",
      "citations": 2,
      "latest": "2021-01-01",
      "doc_url": "https://www.nkis.re.kr/subject_view1.do?otcCd=RB&otcNm=기본연구보고서&otpId=ACPT_000000000028215&otpSeq=0&eoSeq=322248&currentPage=4&searchSelect=&searchWord=&returnPage=newest_list.do&schLclaScsId=&pblYy=&agcNms=과학기술정책연구원&listPerPage=50"
    },
    {
      "org": "Stockholm Environment Institute",
      "country": "Sweden",
      "source_type": "think tank",
      "citations": 2,
      "latest": "2017-11-27",
      "doc_url": "https://www.sei.org/publications/international-transfers-article-6-ndcs/"
    },
    {
      "org": "United Nations Framework Convention on Climate Change",
      "country": "IGO",
      "source_type": "igo",
      "citations": 2,
      "latest": "2025-07-14",
      "doc_url": "https://unfccc.int/documents/648788"
    },
    {
      "org": "Wetenschappelijke Raad voor het Regeringsbeleid",
      "country": "Netherlands",
      "source_type": "government",
      "citations": 2,
      "latest": "2026-01-20",
      "doc_url": "https://www.wrr.nl/documenten/2025/11/26/met-de-mondiale-demografie-mee.-anticiperen-op-krimpend-arbeidsaanbod-in-het-buitenland"
    },
    {
      "org": "Agora Energiewende",
      "country": "Germany",
      "source_type": "think tank",
      "citations": 1,
      "latest": "2023-09-11",
      "doc_url": "https://www.agora-energiewende.de/en/publications/ensuring-resilience-in-europes-energy-transition/"
    },
    {
      "org": "Australian Policy Online",
      "country": "Australia",
      "source_type": "other",
      "citations": 1,
      "latest": "2018-08-19",
      "doc_url": "https://apo.org.au/node/187451"
    },
    {
      "org": "Bipartisan Policy Center",
      "country": "USA",
      "source_type": "think tank",
      "citations": 1,
      "latest": "2013-02-27",
      "doc_url": "https://bipartisanpolicy.org/library/americas-energy-resurgence-sustaining-success-confronting-challenges/"
    },
    {
      "org": "Canadian Centre for Policy Alternatives (CCPA)",
      "country": "Canada",
      "source_type": "think tank",
      "citations": 1,
      "latest": "2022-10-25",
      "doc_url": "https://www.policyalternatives.ca/publications/reports/bet-big"
    },
    {
      "org": "CEEPR",
      "country": "USA",
      "source_type": "think tank",
      "citations": 1,
      "latest": "2025-04-08",
      "doc_url": "https://ceepr.mit.edu/workingpaper/good-spillover-bad-spillover-industrial-policy-trade-and-the-political-economy-of-decarbonization/"
    },
    {
      "org": "Center for Global Development",
      "country": "USA",
      "source_type": "think tank",
      "citations": 1,
      "latest": "2025-12-15",
      "doc_url": "https://www.cgdev.org/publication/forest-worker-quantifying-co2-reduction-contribution-marginal-green-migrant-worker"
    },
    {
      "org": "Centre for Economic Policy Research",
      "country": "UK",
      "source_type": "think tank",
      "citations": 1,
      "latest": "2025-06-18",
      "doc_url": "https://cepr.org/publications/books-and-reports/economic-consequences-second-trump-administration-preliminary"
    },
    {
      "org": "Centre for Economic Transition Expertise (CETEX)",
      "country": "UK",
      "source_type": "think tank",
      "citations": 1,
      "latest": "2025-09-12",
      "doc_url": "https://cetex.org/publications/seven-lessons-for-indias-climate-finance-taxonomy/"
    },
    {
      "org": "Deutsche Gesellschaft für Auswärtige Politik (DGAP)",
      "country": "Germany",
      "source_type": "think tank",
      "citations": 1,
      "latest": "2025-06-25",
      "doc_url": "https://dgap.org/en/research/publications/advanced-technology-europes-strategic-imperative"
    },
    {
      "org": "Deutsches Institut für Wirtschaftsforschung (DIW)",
      "country": "Germany",
      "source_type": "think tank",
      "citations": 1,
      "latest": "2026-01-27",
      "doc_url": "https://www.diw.de/de/diw_01.c.997094.de/publikationen/diskussionspapiere/2026_2153/non-price_criteria_in_renewable_energy_auctions_and_consequences_for_the_european_solar_pv_industry.html"
    },
    {
      "org": "E3G",
      "country": "UK",
      "source_type": "think tank",
      "citations": 1,
      "latest": "2021-04-01",
      "doc_url": "https://www.e3g.org/publications/china-s-14th-five-year-plan/"
    },
    {
      "org": "Ecofiscal",
      "country": "Canada",
      "source_type": "think tank",
      "citations": 1,
      "latest": "2019-06-12",
      "doc_url": "https://ecofiscal.ca/2019/06/12/chinas-climate-challenge-part-2/"
    },
    {
      "org": "Ecologic Institute",
      "country": "Germany",
      "source_type": "think tank",
      "citations": 1,
      "latest": "2023-06-20",
      "doc_url": "https://www.ecologic.eu/19263"
    },
    {
      "org": "ESRC Centre for Climate Change Economics and Policy",
      "country": "UK",
      "source_type": "think tank",
      "citations": 1,
      "latest": "2020-10-30",
      "doc_url": "https://www.cccep.ac.uk/publication/from-rescue-to-recovery-towards-a-sustainable-transition-for-china-after-the-covid-19-pandemic/"
    },
    {
      "org": "Fundação Getulio Vargas",
      "country": "Brazil",
      "source_type": "think tank",
      "citations": 1,
      "latest": "2024-06-06",
      "doc_url": "https://hdl.handle.net/10438/35550"
    },
    {
      "org": "Government of Argentina",
      "country": "Argentina",
      "source_type": "government",
      "citations": 1,
      "latest": "2021-12-22",
      "doc_url": "https://www.argentina.gob.ar/sites/default/files/2022/02/2022_book_nuclearlaw.pdf"
    },
    {
      "org": "Government of India",
      "country": "India",
      "source_type": "government",
      "citations": 1,
      "latest": "2024-09-30",
      "doc_url": "https://nghm.mnre.gov.in/admin/uploads/resources/173069690523453IRENA_Renewable_energy_and_jobs_2024.pdf"
    },
    {
      "org": "Government of Iran",
      "country": "Iran",
      "source_type": "government",
      "citations": 1,
      "latest": "2021-02-16",
      "doc_url": "https://iies.mop.ir/File/ShowFile.aspx?ID=790ea528-0483-4429-a64a-f1da55889a6b"
    },
    {
      "org": "House Committees",
      "country": "USA",
      "source_type": "government",
      "citations": 1,
      "latest": "2021-07-16",
      "doc_url": "https://www.congress.gov/event/117th-congress/house-event/113923"
    },
    {
      "org": "ifo Institut",
      "country": "Germany",
      "source_type": "think tank",
      "citations": 1,
      "latest": "2024-06-19",
      "doc_url": "https://www.cesifo.org/en/publications/2024/working-paper/sequencing-carbon-dioxide-removal-eu-ets"
    },
    {
      "org": "Institut Montaigne",
      "country": "France",
      "source_type": "think tank",
      "citations": 1,
      "latest": "2021-07-01",
      "doc_url": "https://www.institutmontaigne.org/publications/china-trends-9-une-chine-decarbonee-est-elle-possible"
    },
    {
      "org": "Institute for Global Environment Strategies",
      "country": "Japan",
      "source_type": "think tank",
      "citations": 1,
      "latest": "2024-05-01",
      "doc_url": "https://www.iges.or.jp/en/pub/industrial-policy-japan/en"
    },
    {
      "org": "Institute of International and European Affairs",
      "country": "Ireland",
      "source_type": "think tank",
      "citations": 1,
      "latest": "2020-10-20",
      "doc_url": "https://www.iiea.com/publication/course-correction-china-is-going-carbon-neutral/"
    },
    {
      "org": "International Science Council",
      "country": "France",
      "source_type": "think tank",
      "citations": 1,
      "latest": "2021-01-26",
      "doc_url": "https://council.science/publications/rethinking-energy-solutions/"
    },
    {
      "org": "IPCC",
      "country": "IGO",
      "source_type": "igo",
      "citations": 1,
      "latest": "2022-03-08",
      "doc_url": "https://www.ipcc.ch/report/sixth-assessment-report-working-group-3/"
    },
    {
      "org": "Mekong River Commission",
      "country": "IGO",
      "source_type": "igo",
      "citations": 1,
      "latest": "2019-10-22",
      "doc_url": "http://www.mrcmekong.org/assets/Publications/SOBR-v8_Final-for-web.pdf"
    },
    {
      "org": "Middle East Institute (MEI)",
      "country": "USA",
      "source_type": "think tank",
      "citations": 1,
      "latest": "2021-10-19",
      "doc_url": "https://www.mei.edu/publications/sustainable-momentum-china-and-mideast-solar-market"
    },
    {
      "org": "OECD",
      "country": "IGO",
      "source_type": "igo",
      "citations": 1,
      "latest": "2024-10-23",
      "doc_url": "https://dx.doi.org/https://doi.org/10.1787/2b90fa2c-en"
    },
    {
      "org": "Potsdam-Institut für Klimafolgenforschung (PIK)",
      "country": "Germany",
      "source_type": "think tank",
      "citations": 1,
      "latest": "2024-06-03",
      "doc_url": "https://publications.pik-potsdam.de/pubman/item/item_32030_2"
    },
    {
      "org": "REN21",
      "country": "France",
      "source_type": "think tank",
      "citations": 1,
      "latest": "2021-06-14",
      "doc_url": "https://www.ren21.net/wp-content/uploads/2019/05/GSR2021_Full_Report.pdf"
    },
    {
      "org": "State of New York",
      "country": "USA",
      "source_type": "government",
      "citations": 1,
      "latest": "2022-05-30",
      "doc_url": "https://climate.ny.gov/-/media/project/climate/files/Draft-Scoping-Plan-Appendix-G-Integration-Analysis-Technical-Supplement.pdf"
    },
    {
      "org": "The Global Commission on the Economy and Climate",
      "country": "IGO",
      "source_type": "igo",
      "citations": 1,
      "latest": "2018-02-02",
      "doc_url": "https://newclimateeconomy.report/workingpapers/wp-content/uploads/sites/5/2018/02/Building-Thriving-Low-Carbon-Cities-An-Overview-Full-Paper-1.pdf"
    },
    {
      "org": "The Scottish Government",
      "country": "UK",
      "source_type": "government",
      "citations": 1,
      "latest": "2026-01-27",
      "doc_url": "https://www.gov.scot/publications/meeting-scotlands-workforce-needs-transition-net-zero-role-migration-impact-demographic-challenges/"
    },
    {
      "org": "UK Parliament Select Committee Publications",
      "country": "UK",
      "source_type": "government",
      "citations": 1,
      "latest": "2024-05-08",
      "doc_url": "https://committees.parliament.uk/writtenevidence/129843/pdf/"
    },
    {
      "org": "United Nations Environment Programme",
      "country": "IGO",
      "source_type": "igo",
      "citations": 1,
      "latest": "2024-10-21",
      "doc_url": "https://wedocs.unep.org/handle/20.500.11822/46404"
    },
    {
      "org": "VTI",
      "country": "Sweden",
      "source_type": "government",
      "citations": 1,
      "latest": "2023-01-09",
      "doc_url": "https://vti.diva-portal.org/smash/record.jsf?pid=diva2%3A1725636"
    },
    {
      "org": "Wuppertal Institut",
      "country": "Germany",
      "source_type": "think tank",
      "citations": 1,
      "latest": "2025-06-04",
      "doc_url": "https://epub.wupperinst.org/frontdoor/index/index/searchtype/all/docId/8869"
    }
  ],
  "topics": [
    {
      "topic": "Economy",
      "count": 70
    },
    {
      "topic": "Renewable energy",
      "count": 63
    },
    {
      "topic": "Climate change mitigation",
      "count": 57
    },
    {
      "topic": "Climate change",
      "count": 49
    },
    {
      "topic": "Low-carbon economy",
      "count": 49
    },
    {
      "topic": "Energy",
      "count": 43
    },
    {
      "topic": "Greenhouse gas emissions",
      "count": 43
    },
    {
      "topic": "Greenhouse gas",
      "count": 40
    },
    {
      "topic": "Nature",
      "count": 39
    },
    {
      "topic": "Sustainable energy",
      "count": 39
    },
    {
      "topic": "Infrastructure",
      "count": 36
    },
    {
      "topic": "Photovoltaics",
      "count": 36
    },
    {
      "topic": "Natural environment",
      "count": 35
    },
    {
      "topic": "Sustainability",
      "count": 35
    },
    {
      "topic": "Electricity generation",
      "count": 34
    },
    {
      "topic": "Policy",
      "count": 33
    },
    {
      "topic": "Wind power",
      "count": 33
    },
    {
      "topic": "China",
      "count": 32
    },
    {
      "topic": "Economic growth",
      "count": 32
    },
    {
      "topic": "Technology",
      "count": 32
    },
    {
      "topic": "Efficient energy use",
      "count": 31
    },
    {
      "topic": "Solar power",
      "count": 31
    },
    {
      "topic": "Energy development",
      "count": 30
    },
    {
      "topic": "Fossil fuel",
      "count": 29
    },
    {
      "topic": "International Energy Agency",
      "count": 29
    },
    {
      "topic": "Coal",
      "count": 28
    },
    {
      "topic": "Subsidy",
      "count": 28
    },
    {
      "topic": "European Union",
      "count": 27
    },
    {
      "topic": "Electric vehicle",
      "count": 26
    },
    {
      "topic": "Paris Agreement",
      "count": 26
    },
    {
      "topic": "Air pollution",
      "count": 25
    },
    {
      "topic": "Electrical grid",
      "count": 25
    },
    {
      "topic": "Fuel",
      "count": 25
    },
    {
      "topic": "Innovation",
      "count": 25
    },
    {
      "topic": "Transport",
      "count": 25
    },
    {
      "topic": "Carbon price",
      "count": 24
    },
    {
      "topic": "Market (economics)",
      "count": 24
    },
    {
      "topic": "Carbon capture and storage",
      "count": 22
    },
    {
      "topic": "Energy transition",
      "count": 22
    },
    {
      "topic": "Tax",
      "count": 22
    }
  ],
  "timeline": [
    {
      "year": "2013",
      "citations": 1
    },
    {
      "year": "2014",
      "citations": 1
    },
    {
      "year": "2017",
      "citations": 4
    },
    {
      "year": "2018",
      "citations": 3
    },
    {
      "year": "2019",
      "citations": 3
    },
    {
      "year": "2020",
      "citations": 10
    },
    {
      "year": "2021",
      "citations": 16
    },
    {
      "year": "2022",
      "citations": 10
    },
    {
      "year": "2023",
      "citations": 15
    },
    {
      "year": "2024",
      "citations": 16
    },
    {
      "year": "2025",
      "citations": 10
    },
    {
      "year": "2026",
      "citations": 5
    }
  ],
  "countries": [
    {
      "country": "IGO",
      "citations": 27
    },
    {
      "country": "USA",
      "citations": 15
    },
    {
      "country": "UK",
      "citations": 10
    },
    {
      "country": "Germany",
      "citations": 7
    },
    {
      "country": "France",
      "citations": 5
    },
    {
      "country": "Switzerland",
      "citations": 5
    },
    {
      "country": "South Korea",
      "citations": 4
    },
    {
      "country": "EU",
      "citations": 3
    },
    {
      "country": "Japan",
      "citations": 3
    },
    {
      "country": "Sweden",
      "citations": 3
    },
    {
      "country": "Austria",
      "citations": 2
    },
    {
      "country": "Canada",
      "citations": 2
    },
    {
      "country": "Netherlands",
      "citations": 2
    },
    {
      "country": "Argentina",
      "citations": 1
    },
    {
      "country": "Australia",
      "citations": 1
    },
    {
      "country": "Brazil",
      "citations": 1
    },
    {
      "country": "India",
      "citations": 1
    },
    {
      "country": "Iran",
      "citations": 1
    },
    {
      "country": "Ireland",
      "citations": 1
    }
  ],
  "types": [
    {
      "source_type": "think tank",
      "citations": 41
    },
    {
      "source_type": "igo",
      "citations": 27
    },
    {
      "source_type": "government",
      "citations": 25
    },
    {
      "source_type": "other",
      "citations": 1
    }
  ],
  "mention_types": [
    {
      "type": "Policy citation",
      "count": 87
    },
    {
      "type": "Name mention",
      "count": 7
    }
  ]
};
